name: flutter_serial_communication_platform_interface
description: Platform interface for the flutter_serial_communication plugin.
version: 0.2.6
homepage: https://github.com/farellsujanto/flutter_serial_communication

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
