name: flutter_serial_communication_desktop_support
description: "Windows, Linux & MacOS implementation of flutter_serial_communication"
version: 0.0.1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_serial_communication_platform_interface:
    path: ../plug_platform_interface
  dylib: ^0.3.3
  ffi: ^2.1.3

dev_dependencies:
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: FlutterSerialCommunicationDesktopSupportPlugin
        dartPluginClass: FlutterSerialCommunicationDesktopSupport
      # linux:
      #   ffiPlugin: true
      #   dartPluginClass: FlutterSerialCommunicationDesktopSupport
      # windows:
      #   ffiPlugin: true
      #   dartPluginClass: FlutterSerialCommunicationDesktopSupport
