name: flutter_serial_communication
description: Library for serial communication.
version: 0.2.6
homepage: https://github.com/farellsujanto/flutter_serial_communication

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_serial_communication_platform_interface:
    path: ../plug_platform_interface
  flutter_serial_communication_android_support:
    path: ../plug_android_support
  flutter_serial_communication_desktop_support:
    path: ../plug_desktop_support

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_serial_communication_android_support
      macos:
        default_package: flutter_serial_communication_desktop_support
      windows:
        default_package: flutter_serial_communication_desktop_support
      linux:
        default_package: flutter_serial_communication_desktop_support
      # web:
      #   default_package: flutter_serial_communication_web_support
